name: flutter_webview_plugin
description: Plugin that allow Flutter to communicate with a native Webview.
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/dart-flitter/flutter_webview_plugin
version: 0.0.3

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter
